name: Build and Release with Maven

on:
  workflow_dispatch:        # manual trigger
  push:
    branches: [ main, master ]   # bleeding-edge builds
    tags:
      - 'v*'                     # release builds when you push a tag like v0.1.0-alpha

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: false

      - name: Package modules
        id: package
        run: mvn -B clean package -P=-lwjgl-natives-linux-amd64,lwjgl-natives-windows-amd64 --file pom.xml --no-transfer-progress

      - name: Publish client artifact
        uses: ./.github/actions/upload_build
        if: ${{ always() && steps.package.outcome == 'success' }}
        with:
          SOURCE_FILE: 'client/target/client-*.jar'
          DEST_NAME: 'client-${{ github.ref_name }}.jar'

      - name: Publish server artifact
        uses: ./.github/actions/upload_build
        if: ${{ always() && steps.package.outcome == 'success' }}
        with:
          SOURCE_FILE: 'server/target/server-*.jar'
          DEST_NAME: 'server-${{ github.ref_name }}.jar'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          make_latest: true
          files: |
            client/target/client-*.jar
            server/target/server-*.jar
